name: Publish TileServer Docker image

on:
    push:
        branches:
            - zarr-tiff-wsi-reader-docker

jobs:
    build:
        runs-on: ubuntu-22.04
        timeout-minutes: 40

        steps:
            -   uses: actions/checkout@v3

            -   name: Login to Github
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.PAT }}


            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3.8.0

            -   name: Build Docker Image
                uses: docker/build-push-action@v6.12.0
                with:
                    context: ./container/
                    file: ./Dockerfile
                    tags: tileserver:latest
                    platforms: linux/amd64
                    outputs: type=docker
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
